### ISSUE TITLE
Add option to select download folder

### ISSUE THREAD

**Issue by bertyhell** [bertyhell/PlaylistDownloader#1]

**Comment by LukeOwlclaw** [comment]
I forked this project I did some improvements, including "Add option to select download folder"
--> https://github.com/LukeOwlclaw/PlaylistDownloader
In case anybody is interested...

@bertyhell If you like, feel free to integrate the changes into your branch.

**Comment by bertyhell** [comment]
Sure, could you submit it as a pull request?

**Comment by bertyhell** [comment]
available under https://github.com/bertyhell/PlaylistDownloader/releases/tag/1.9.2
